application: eyeunite
version: dev
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /
  static_files: static/views/index.html
  upload: static/views/index.html
- url: /.*
  script: main.py
